# This is a basic workflow to help you get started with Actions

name: 5-in-a-row-game-testing

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
    - main 
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  installpython:
    name: Install Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
  testing: 
      name: Testing the Game
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Running Tests
          run: python3 -m unittest testing/*
        
